### ISSUE TITLE
Handle complex arguments

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq.cr#1]
The `perform_types` macro handles the marshaling of JSON args to the `perform` method but can't handle Arrays or Hashes yet, it needs to properly recurse.

**Comment by mperham** [comment]
@asterite Any tips on how to handle this?  I'm ok only handling one-level-deep `Array(JSON::Type)` and `Hash(String, JSON::Type)` but it would be nice if it could handle arbitrarily-deep Hashes.  If the user declares this:

```ruby
def perform(x : Array(Int64), y : Hash(String, Float64))
```

Could I do something like this to handle the Array?

```ruby
      macro method_added(a_def)
        \{% if a_def.name.id == "perform".id %}
          def _perform(args : Array(JSON::Type))
            perform(
              \{% for arg, index in a_def.args %}
                \{% if arg.restriction %}
                 \{% if arg.restriction.is_a?(Array) %}
                    args[\{{index}}].map{|x| x.as(\{{arg.restriction.inner_type}}) },
                  \{% else %}
                    args[\{{index}}].as(\{{arg.restriction}}),
                  \{% end %}
                \{% else %}
                  \{{ raise "argument '#{arg}' must have a type restriction" }}
                \{% end %}
              \{% end %}
            )
          end

**Comment by asterite** [comment]
I would actually allow *any* type as an argument, why restrict it to just `JSON::Type`? Just invoke `Type.from_json(String)` or `Type.new(JSON::PullParser)`.

I would make `Job.load` to accept a String, not a Hash, create a PullParser and read from that, reading args as a raw string. I'd use JSON.mapping to make that easier (why did you removed `JSON.mapping`? Maybe it was because you needed unions in mappings? If that's the case, you'll be happy to know that 0.18.0 is around the corner and supports that 😄). Then using named tuples matching the method arguments I would re-constructor the job. The code is a bit for me to modify or send a PR, but I'll show you some code so you have an idea of what I'm talking about ([in play](https://play.crystal-lang.org/#/r/11lv)):

```crystal
require "json"

module Worker
  macro included
    macro method_added(a_def)
      \{% if a_def.name.id == "perform".id %}
        def _perform(%data : String)
          # We define a tuple with types from each of the arguments.
          # For example, if the args are `name : String, age : Int32`
          # we generate `tuple = Tuple(String, Int32)`.
          %type_tuple = Tuple(\{{
                                a_def.args.map do |arg|
                                  if arg.restriction
                                    arg.restriction
                                  else
                                    raise "argument '#{arg}' must have a type restriction"
                                  end
                                end.join(", ").id
                              }})

          # Then we parse the JSON to this tuple
          %tuple = %type_tuple.from_json(%data)

          # And splat it into `perform`
          perform(*%tuple)
        end
      \{% end %}
    end
  end
end

class Worker1
  include Worker

  def perform(name : String, age : Int32)
    pp name, age
  end
end

worker1 = Worker1.new
worker1._perform(%(["John", 30]))

class Point
  JSON.mapping({x: Int32, y: Int32})
end

class Circle
  JSON.mapping({radius: Int32, diameter: Int32})
end

class Worker2
  include Worker

  def perform(point : Point, circle : Circle)
    pp point, circle
  end
end

worker2 = Worker2.new
worker2._perform(%([{"x": 10, "y": 20}, {"radius": 3, "diameter": 4}]))

# Now to use it when the arguments array is embedded inside another JSON

class Job
  JSON.mapping({
    jid: String,
    # This basically keeps the raw string from the JSON
    args: {type: String, converter: String::RawConverter},
  })
end

job = Job.from_json(%({"jid": "123", "args": [{"x": 10, "y": 20}, {"radius": 3, "diameter": 4}]}))
puts job.args

worker2._perform(job.args)
```

Is this of any help?

**Comment by mperham** [comment]
The problem with `JSON.mapping` is that the Job needs to parse from a Hash that can contain unknown values.  I need unrecognized Hash keys to be placed into an `extras : Hash(String, JSON::Type)` attribute.  The Sidekiq job format in Redis is a JSON hash which allows arbitrary key/value pairs which can be used to control server-side features added by 3rd party extensions, unknown to Sidekiq.  The `skip` behavior would lose those pairs.

**Comment by mperham** [comment]
And I see where you are going with the tuples but part of Sidekiq's design [explicitly recommends against complex structures as arguments](https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple).  This keeps Sidekiq cross-platform and multi-lingual.

**Comment by asterite** [comment]
We could probably enhance `JSON.mapping` to keep extra attributes in a separate attribute, should be really easy to do. It can be done manually with `JSON::PullParser` but it's a lot more tedious. Would that work?

Another alternative is to create an object by "parsing" a `JSON::Any` object. This was suggested by @jhass a few times. I think it could work but it feels a bit (just a bit) hacky to me.

**Comment by mperham** [comment]
I've seen JSON parsers use a `_` attribute to store unexpected pairs.  Seems like a good idea to me and won't collide with any named properties.

**Comment by asterite** [comment]
What I mean with complex structures is that maybe you can do:

```crystal
point = {"lat" => 10, "lng": 20}
event = "eartquake"
some.async.perform(point, event)
```

In Ruby it's easy, you just do:

```ruby
def perform(point, event)
  point["x"]
end
```

In Crystal you could represent it as a `Hash(String, Int32)`:

```crystal
def perform(point : Hash(String, Int32))
  point["x"]
end
```

however, creating a Hash when it's known to just have "x" and "y" attributes with numbers is both more verbose, a bit less type safe, and less efficient. Being able to express a JSON object as a Crystal type will make this possible, but this is not promoting storing complex objects, just doing things "The Crystal way" (type safe and efficient). You could in fact keep saying that only JSON::Any types are allowed, but use this approach (it'll be simpler).

With extra I mean something like this:

```crystal
class PointWithExtra
  JSON.mapping({
    x: Int32,
    y: Int32,
  }, store_unknown_attributes_in: extra)

  # generates:
  # @extra : JSON::Any
  #
  # and instead of skip it stores data in `extra`
end

point = PointWithExtra.from_json(%({"x": 1, "y": 2, "z": 3, "w": "hello"}))
point.x # => 1
point.y # => 2
point.extra # => {"z": 3, "w": "hello"} (as a JSON::Type)
```

**Comment by mperham** [comment]
That looks pretty awesome, I'm all for efficient and idiomatic structures and patterns.

**Comment by asterite** [comment]
Two more questions:
1. Could you point me to the code that stores/accesses that extra data?
2. Why not store all the extra data as a separate attribute? I guess the reason is backwards-compatibility?

**Comment by mperham** [comment]
Here's an example of a Ruby extension:

https://github.com/mhenrixon/sidekiq-unique-jobs

The basic pattern is a [middleware](https://github.com/mperham/sidekiq/wiki/Middleware) pipeline -- client-side middleware can add properties to the job hash before pushing it to Redis and a server middleware can execute code and access those properties around the job processing:

```ruby
class MyClientMiddleware
  def call(job : Sidekiq::Job, ctx : Sidekiq::Context)
    job.something = !!some_logic
    yield
  end
end

class MyServerMiddleware
  def call(job : Sidekiq::Job, ctx : Sidekiq::Context)
    if job.something
      yield
    else
      # don't yield, the job is effectively "thrown away"
    end
  end
end
```

Sidekiq implements several of its features as middleware plugins:

https://github.com/mperham/sidekiq.cr/blob/master/src/sidekiq/server/retry_jobs.cr
https://github.com/mperham/sidekiq.cr/blob/master/src/sidekiq/server/middleware.cr

My guess is the idiomatic Crystal thing to do is have each middleware extension declare its needed properties to Sidekiq::Job so they can be parsed from JSON too.

I do need to keep multi-platform support in mind: a job hash might contain an attribute that Crystal didn't know about at compile time.  The attribute's probably not relevant to the job execution but it would still be nice if the Web UI could show the entire set of job attributes, even if not known at compile time, thus the need for the "extras" attribute.
