### ISSUE TITLE
Remove DUMP binary fixtures

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq.cr#10]
These don't work across the 3.0 / 3.2 boundary.  Create the fixture data programmatically or remove the tests completely.

**Comment by mperham** [comment]
Oh right, I dumped the data because it's an exact copy of what Sidekiq.rb leaves in Redis and I wanted to verify that Crystal could deserialize it.  Hmmm, how to verify Crystal <-> Ruby ....

**Comment by jhass** [comment]
How about a Ruby script (depending on sidekiq) that generates them? Then anybody with the right Redis version at hand can contribute new dumps.

**Comment by mperham** [comment]
Hmmm, I like your idea, create a script to generate the fixtures once, genius! Starting a long weekend now but will throw something together next week.
