### ISSUE TITLE
Can't send job to queue

### ISSUE THREAD

**Issue by confact** [mperham/sidekiq.cr#109]
I have been trying to do like this:
```
    job = Sidekiq::Job.new
    job.klass = "ReindexUserWorker"
    job.queue = "user"
    job.args = [self.id].to_json
    client = Sidekiq::Client.new
    puts client.push(job)
 ```
 It gives jid and says nothing went bad. But no job got to the queue.

I also tried this:
```
ReindexUserWorker.async.perform(1_i32)
```

But nothing there either. I got jid but no job in the queue.

UPDATE:
Sidekiq's server (ruby) version is 6.1.3

**Comment by confact** [comment]
Got it to work, it was third party gems on the ruby part that was blocking the jobs. 

Thanks for a good lib on crystal, even if it is just in maintenance mode!

**Comment by hugopl** [comment]
Nobody is working on new features but this doesn't mean that people aren't allowed to propose new features, especially if who proposes plan to implement them :wink:
