### ISSUE TITLE
Error: method Redis::TransactionApi#zadd must return (Int64 | String) but it is returning Redis::Future

### ISSUE THREAD

**Issue by CapnBerni** [mperham/sidekiq.cr#111]
Hello,

I'm doing some testing with crystal and sidekick.cr and it looks like I got an issue with redis (error in title).

I join the log trace here:
[trace.log](https://github.com/mperham/sidekiq.cr/files/7009887/trace.log)

Crystal 1.1.1
dependencies:
  redis:
    github: stefanwille/crystal-redis
    version: ~> 2.6
    
Reproduce:
clone repo: https://github.com/mperham/sidekiq.cr
shards install
crystal run examples/sidekiq.cr

**Comment by CapnBerni** [comment]
Issue opened on redis: https://github.com/stefanwille/crystal-redis/issues/121

**Comment by CapnBerni** [comment]
Fixed in crystal-redis

**Comment by hugopl** [comment]
So I think we should bump the required crystal-redis version.

**Comment by hugopl** [comment]
However... it works with crystal-redis 2.6.0, the issue only happen with crystal-redis 2.8.0 and 2.8.1 that had this breaking change that end up being a regression, so I think we are good and nothing need to be changed on sidekiq side.
