### ISSUE TITLE
Add Web UI

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq.cr#12]
Sidekiq's Web UI is based on Sinatra.  Investigate building a native Crystal version using Kemal and ecr views instead.

Requires #11.

**Comment by sdogruyol** [comment]
I'd be happy to help you about any Kemal related question 👍

**Comment by mperham** [comment]
The top-level DSL seems really cool at first glance but IMO it takes away a lot of capabilities.  I'm really missing a more idiomatic OOP-based webapp style.  Sinatra now provides something like this:

```ruby
class Sidekiq::Web < Kemal::Base
  public_folder "..."

  get "/" do |env|
  end
end

# Allow multiple webapps to be mounted
Kemal.serve("localhost", 8080, {
  "/sidekiq" => Sidekiq::Web
  "/something-else" => Another::Web
})
```

With that style, you could also implement testing helpers, a la Rack::Test:

```
require "kemal/spec"

def app
  Sidekiq::Web
end

describe "web" do
  it "should work" do
    resp = app.route(:get, "/")
    resp.code.should eq(200)
  end
end
```

**Comment by sdogruyol** [comment]
Yeah, i'm pretty aware of that and would like to implement the `classic` Sinatra style which lets you mount multiple apps.

**Comment by mperham** [comment]
Done!

I was able to implement [GET and POST helper methods](https://github.com/mperham/sidekiq.cr/blob/master/spec/web_spec.cr#L558) to make the Ruby port easier.  Allows me to spec like this:

```ruby
    post "/scheduled/#{job_params(*params)}", {"add_to_queue" => "true"}
    assert_equal 302, last_response.status_code
    assert_equal "/scheduled", last_response.headers["Location"]

    get "/queues/default"
    assert_equal 200, last_response.status_code
    assert_match(/#{params.first["args"][2].to_s}/, last_response.body)
```

**Comment by danielpclark** [comment]
>     # Allow multiple webapps to be mounted
>     Kemal.serve("localhost", 8080, {
>       "/sidekiq" => Sidekiq::Web
>       "/something-else" => Another::Web
>      })

Did this get implemented in a mountable way for Kemal?  I've been writing Rails-like controllers with Kemal in [danielpclark/crystal-rails-template](https://github.com/danielpclark/crystal-rails-template)

```crystal
require "../app/controllers/*"

module Railslike
  module Routes
    include Controllers
    get "/", &IndexController.to_proc
    error 404, &Error404Controller.to_proc
  end
end
```

Where each method I define (`to_proc` in this instance) returns something like:

```crystal
def self.to_proc
  ->(env : HTTP::Server::Context){
    controller = new(env)         # Evaluated in other controller context of type BaseController
    controller.render(controller) # Pass context into layout renderer
  }   
end 
```

This works very well for me.  But I digress, has this been implemented to run Sidekiq mounted in an existing server instance of Kemal?

**Comment by sdogruyol** [comment]
@danielpclark unfortunately, this is not implemented. Kemal only allows single app per single process (for now)
