### ISSUE TITLE
restrict type on sender too

### ISSUE THREAD

**Issue by kostya** [mperham/sidekiq.cr#13]
```crystal
class MyWorker
  include Sidekiq::Worker

  def perform(x : Int64)
    logger.info "hello!"
  end
end

MyWorker.async.perform(1_i64)
MyWorker.async.perform("bla")
```

compiled, but expected compile error

**Comment by mperham** [comment]
I'm not sure how to do that.  The Worker.async.perform chain calls this method, which has no type restrictions:

https://github.com/mperham/sidekiq.cr/blob/master/src/sidekiq/job.cr#L104
