### ISSUE TITLE
Findings while working through 'Getting Started'

### ISSUE THREAD

**Issue by wimrijnders** [mperham/sidekiq.cr#23]
Hi mperham,

I confess I am a total newbie to crystal. Yesterday was the first time I dabbled with it in any way.

I've worked my way through the 'Getting Started' page for sidekiq very literally. Meaning, that I do exactly what the text specifies. The points below are the issues I found along the way.

I kindly request that the text of the page gets adjusted, so that newbies like me have a chance getting the examples to work.

### Redis needs to be installed
This may sound obvious, but is not mentioned anywhere. Also, a reference to getting and installing it may be appropriate.

### Example sidekiq.cr doesn't output anything
I got it running as specified by text, but no output from the workers ensued.
Only after downloading the examples and running the sidekiq.cr did I get anything useful. I surmise that the code difference between the example code and the code as given in the text is significant.
Please update the code in the text so that it works in one go.

### Example web.cr doesn't compile
This gives the following error:

    Error opening file '/home/wim/projects/try/crystal/try/sample/libs/sidekiq/sidekiq/../../web/views/dashboard.ecr' with mode 'r': No such file or directory (Errno)

Only after an irc consult did it become apparent to me that certain assets where missing for web.cr.

### Repo examples work fine locally
In the end, I gave up, cloned the repo and ran the examples from there. This worked perfectly, but nullifies the content of the 'Getting Started' page. It might as well not exist.

Besides the above points, I would suggest a 'Quick Start' at the top of the 'Getting Started' page, with terse instructions as to how to run the repo examples.

----

Thank you for your attention; I hope it's clear I'm not trying to critique here. I simply wish for my successors to have a better experience.

**Comment by mperham** [comment]
Thanks for the feedback and kudos on getting things working.  You don't sound like a newbie to me!

Yeah, there's some stuff I forgot to document as an expert and a few existing issues.  For instance, the web asset thing is a [known issue](https://github.com/mperham/sidekiq.cr/issues/14).  I'll polish things up over the next week and document it here.

**Comment by wimrijnders** [comment]
While I am not a newbie programmer, I AM shiny sparkling new to crystal and everything related.

I decided to jump into the deep end and tackle a blog of yours to see how far I could get. I left a message there as well so you can see I succeeded in getting it to work.

Thank you for listening!

**Comment by mperham** [comment]
Ok, fixed two major issues and updated the Getting Started page.  Thank you again for your feedback!
