### ISSUE TITLE
Sidekiq.cr breaks "Busy" tab for Ruby Web UI

### ISSUE THREAD

**Issue by Agiley** [mperham/sidekiq.cr#24]
First of all, thanks for Sidekiq.cr - wouldn't have tried Crystal without it!

There seems to be an issue with the "Busy"-tab for the Ruby Web UI when running Sidekiq.cr:

`TypeError at /sidekiq/busy
can't convert String into an exact number
file: calculations.rb location: at line: 45`

This seems to be related to [https://github.com/mperham/sidekiq/blob/master/web/views/busy.erb#L90](https://github.com/mperham/sidekiq/blob/master/web/views/busy.erb#L90).

If I replace `<%= relative_time(Time.at(msg['run_at'])) %>` with `<%= msg['run_at'] %>` the "Busy" tab works again.

If I take one of the timestamps printed in the "Started" column and run it in the ruby console with Time.at:
`$ Time.at("1466511737")`
`TypeError: can't convert String into an exact number`

So it seems that the Sidekiq Web UI for Ruby can't handle the data for 'run_at' inserted from Sidekiq.cr?

**Comment by mperham** [comment]
Thank you for the report, good to see people starting to poke it!
