### ISSUE TITLE
Optimize logging output

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq.cr#27]
I noticed that setting the benchmark logger level to WARN, the jobs per sec went from 15k to 36k!

To reproduce:

1. Run `make bench`.
2. Edit bench/load.cr and change the log level on line 26 from INFO to WARN.
3. Repeat 1.

I optimized the [Logger::Formatter here](https://github.com/mperham/sidekiq.cr/blob/master/src/sidekiq/logger.cr#L7) to stream to the IO but it didn't appear to make a difference.  The logger is [used here](https://github.com/mperham/sidekiq.cr/blob/master/src/sidekiq/server/middleware.cr#L10).  Any ideas on how to minimize the log overhead?

**Comment by asterite** [comment]
I'll soon take a look, try to run a profiler on it and see what can be optimized. It would be super cool to make it do more jobs per second :-)

**Comment by asterite** [comment]
I tried to optimize it but couldn't find a single bottleneck. The time is spread across converting the time to a string, appending to the IO, etc. I don't think there's much that can be done.

**Comment by mperham** [comment]
Ugh, it's such a huge difference; I'm surprised there's no low-hanging fruit to pick.  Thanks for looking at it.

**Comment by mperham** [comment]
BTW I tried turning off the GC and it actually made it slower.  Maybe heap size can affect performance?  Logging appears to generate ~20% of the garbage.
