### ISSUE TITLE
sidekiq_options

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq.cr#3]
The sidekiq_options method for setting arbitrary worker options doesn't exist.  Rethink how this could be done.

```ruby
class SomeWorker
  include Sidekiq::Worker
  sidekiq_options queue: 'foo', unique_for: 10.minutes
```

**Comment by jhass** [comment]
Given `queue: 'foo', unique_for: 10.minutes` is a named tuple literal, I could imagine a simple macro that just defines a well known class method that returns it
```cr
  def _sidekiq_options
    {queue: 'foo', unique_for: 10.minutes}
  end
```
The `included` macro of `Sidekiq::Worker` would probably need to set an empty default (empty tuple creation will be possible with Crystal 0.18 latest, `nil` should work as default too though).

That could later then be splatted into a method on `Job` or whatever should process or hold the metadata.

```cr
  def assign_worker_metadata(*, queue = "default" : String, unique_for = nil : Time?)
  end

assign_worker_metadata(**klass._sidekiq_options)
```

The benefit over just accessing the keys directly is a fairly concise way to do typechecking for the options.

Anyway, just some first rough thoughts without looking too deeply at the current code.

**Comment by mperham** [comment]
@jhass The issue is that the options are completely free-form.  The user must be able to put `foo: "xyz"` in there if they want too.  I think I can limit the signature to Hash(String, JSON::Type) but those contents need to be merged into the resulting Sidekiq::Job payload.  Since I can't list arbitrary keys in the JSON.mapping, there's some redesign that needs to take place.

**Comment by jhass** [comment]
Ah, I didn't realize they are.

**Comment by mperham** [comment]
Alternate API:

```ruby
class SomeWorker
  include Sidekiq::Worker
  sidekiq_options do |job|
    job.queue = 'foo'
    job.unique_for = 10.minutes
  end
```

Still need to determine how to add dynamic properties to Sidekiq::Job within the JSON.mapping.  It would be nice if JSON.mapping were additive so we could do this so that extensions could add type-safe properties to the Job at compile-time:

```ruby
class Sidekiq::Job
  JSON.mapping({
    jid: String,
    foo: Bool,
  })
end

# in another file, reopen and add more attributes
class Sidekiq::Job
  JSON.mapping({
    unique_for: Time::Span?
  })
end
```
