### ISSUE TITLE
Run worker with perform_at

### ISSUE THREAD

**Issue by nobilik** [mperham/sidekiq.cr#36]
Hello Mike, 
I'm trying to launch worker
`OkPhotos::TopPhotoUpdateWorker.async.perform_at(2.minutes.from_now, group)`

but I've got an error:

```
instantiating '_perform_at(Time, String)'
in ./libs/sidekiq/sidekiq/job.cr:87: no overload matches 'OkPhotos::TopPhotoUpdateWorker::PerformProxy#perform_in' with types Float64, String
Overloads are:
 - OkPhotos::TopPhotoUpdateWorker::PerformProxy#perform_in(interval : Time::Span, group : Hash(String, Array(String) | String))

      perform_in(interval.epoch_f, args)
      ^~~~~~~~~~

```
`perform_in` works well.

If I do something wrong? Sorry, it's my first issue)

**Comment by mperham** [comment]
Get rid of the "async" call. Just Worker.perform_at or Worker.perform_in

**Comment by nobilik** [comment]
When I run it without async: 
 ```
undefined method 'perform_in' for OkPhotos::GroupTopPhotoUpdateWorker:Class
     OkPhotos::GroupTopPhotoUpdateWorker.perform_in(2.minutes, group)
                                         ^~~~~~~~~~
```

But when I run `OkPhotos::GroupTopPhotoUpdateWorker.async.perform_in(2.minutes, group) `everything works as expected. About perform_at, it doesn't work in both variants.

**Comment by mperham** [comment]
You need to include Sidekiq::Worker in your class to get those methods.

**Comment by mperham** [comment]
Oh snap, I didn't realize this was the crystal version. Ignore what I've said.

**Comment by waghanza** [comment]
@nobilik still having troubles ?

**Comment by nobilik** [comment]
@waghanza I'm not sure) I've released my project without Sidekiq at last.

**Comment by waghanza** [comment]
@nobilik so can you close this issue ?
