### ISSUE TITLE
Rework JSON payload impl

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq.cr#42]
Currently the JSON payload defined in Sidekiq::Job is static and cannot be extended.  Rework the impl based on the new JSON.mapping capabilities wrt the `finished` macro so that applications and 3rd party middleware can introduce new fields into the job payload to be parsed automatically.  This is one of the major failings that keeps Sidekiq.cr from working as well as Sidekiq.rb.

https://github.com/crystal-lang/crystal/pull/3612
https://github.com/mperham/sidekiq.cr/blob/master/src/sidekiq/job.cr#L25

**Comment by Schniz** [comment]
Can you elaborate?

**Comment by Schniz** [comment]
oh, you mean that every Worker can define `extra_parameters` that the `JSON.mapping` will understand?

**Comment by mperham** [comment]
Yes. More specifically, third-party middleware could add JSON parameters that they expect to work with.  For instance, Sidekiq.rb ships with a i18n middleware that uses a "locale" parameter:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/i18n.rb#L13

**Comment by hugopl** [comment]
I implemented it using the [JSON::Unmapped](https://crystal-lang.org/api/0.36.1/JSON/Serializable/Unmapped.html) on Job class, so the middleware on server side can get the value, so things like the i18n middleware above should now be possible.

**Comment by hugopl** [comment]
Implemented in a4b6384220256704d1b045bea057dbdd00ca6f0d.
