### ISSUE TITLE
Release latest changes

### ISSUE THREAD

**Issue by drujensen** [mperham/sidekiq.cr#44]
Could you provide a release of the latest changes?

**Comment by mperham** [comment]
Hi Dru, I hope you'll be a little patient with me and explain more.  Does master work ok for you and you just want a tag?  Are there changes I can make to make the Web UI work better with Kemalyst?

**Comment by drujensen** [comment]
Hi Mike,

I found a way of deploying the sidekiqweb using the master branch via a docker image so I have it working from master now.  I didn't realize you could get a tar.gz of the master branch from github before I opened this request.

An obvious concern is stability of the master branch.  Unfortunately the v0.5.0 release doesn't compile so I can't use your latest released version which would be preferred.

You can find the docker image here: https://hub.docker.com/r/drujensen/sidekiqweb/   Not sure if you will officially support a docker image for the sidekiqweb front-end.

I forked from sidekiq.cr and created [sidekiq-cli.cr](https://github.com/drujensen/sidekiq-cli.cr) which removes the web stuff so I don't have to carry those shard dependencies in Kemalyst.  I just need to try and keep it up-to-date with your latest fixes.  I was hoping you would separate the cli/server from the web interface but I understand why you may not want multiple repositories.

Everything is working great and I'm excited I found a way to integrate sidekiq.cr with Kemalyst.  Now you can easily generate a `job` and have sidekiq.cr run them in the background.  It's so fast and light weight that I can see people using this as a replacement for the ruby version.

I have used sidekiq and rescue on many rails projects and have had queues backup on critical notifications spending weekends trying to fix them.  It was always a battle to try and optimize the jobs and keep them as lightweight as possible.  I'm hopeful this may be a solution for developers that run into similar issues.

If you don't want to tag a release at this point, you can close this issue.

Thanks,
Dru

**Comment by mperham** [comment]
I can arbitrarily mark HEAD as v0.5.1, especially since I know it works for you.  Not much has changed but I did polish things up and fix the compilation issues.  As you note, I don't want multiple repos.

If sidekiq.cr and Kemalyst both depend on Kemal, why are the shard dependencies an issue?

**Comment by drujensen** [comment]
Mike, good question.  

It started out as running on top of Kemal but eventually forked with its own set of middleware.  There are a couple components that are the same but the router has changed to support chaining HTTP:Handlers before and after the routes.  There are a couple of other differences that required forking.

I'm hopeful I can bring it back to being a direct dependency with Kemal.  I'm hoping to discuss ideas with them in SF this week.

Question, do you envision others wanting to use sidekiq.cr without the Kemal dependency?  It seems like other web frameworks (Amethyst) or backend micro-services would want to compile the sidekiq-cli (redis, pool) without wanting the Kemal stack as well.  It slows down compile time and adds bloat to the final binary that is unnecessary, right?

**Comment by mperham** [comment]
It's only unnecessary if you don't want to use the Web UI.  Most developers afaik want to see the Web UI.

Sidekiq.rb has been updated to use only Rack, not Sinatra.  If Crystal had the same sort of abstraction (mountable HTTP endpoints, sessions), I'd be happy to see a PR which simplifies the Web UI and removes Kemal.

v0.6.1 has been tagged.

**Comment by drujensen** [comment]
👍 Thanks for the release.
