### ISSUE TITLE
Idea: Extract Sidekiq Web to a separate shard

### ISSUE THREAD

**Issue by katafrakt** [mperham/sidekiq.cr#59]
Sidekiq Web UI depends on Kemal. However, in Crystal community there are other web frameworks, such as Lucky or Amber. It would be cool to be able to use Sidekiq in them. Currently, fortunately, it's possible. But in the past I used to stumble upon errors coming from version mismatches between Kemal dependencies and Amber dependencies, leading me to be unable to do `shards install`.

Since I don't need Web UI in my Amber/Lucky project (if any, Sidekiq Web is run and deployed separately), it would be good to get rid of those dependencies and easiest way is to extract Sidekiq Web from main sidekiq.cr repository. I had to do it before on my fork and it's not that hard.

What do you think about it?

**Comment by mperham** [comment]
I would be fine with a PR which moves to the stdlib. Not interested in something which extracts the UI to a separate shard.

**Comment by drujensen** [comment]
@katafrakt I also had to fork this repo to remove the UI.  https://github.com/kemalyst/sidekiq-cli.cr

Then i created a docker image to run the UI separate from the framework. https://github.com/kemalyst/docker-sidekiqweb

It was my only option at the time. There were conflicts between Amber (used to be called Kemalyst) and SideKiq.

I haven't tried this in a while but agree that it would be nice if this was separate.

**Comment by mperham** [comment]
@drujensen I don't mind a fork but please update the readme to indicate you are the maintainer and not me.

**Comment by drujensen** [comment]
@mperham I think its clear its a fork.  I will be archiving it.
