### ISSUE TITLE
No need for `perform_types`

### ISSUE THREAD

**Issue by asterite** [mperham/sidekiq.cr#6]
I'm having some troubles having the specs pass (do I need a specific redis version?) but one thing you can do to simplify the definition of workers is to put this in the `macro included` of `Sidekiq::Worker`:

```crystal
macro method_added(a_def)
  \{% if a_def.name.id == "perform".id %}
    def _perform(args : Array(JSON::Type))
      perform(
        \{% for arg, index in a_def.args %}
          \{% if arg.restriction %}
            args[\{{index}}].as(\{{arg.restriction}}),
          \{% else %}
            \{{ raise "argument '#{arg}' must have a type restriction" }}
          \{% end %}
        \{% end %}
      )
    end
  \{% end %}
end
```

And the remove the `perform_types` macro. This will make it so that when a user defines `perform`, the macro will automatically define `_perform` using `perform`'s arguments and types. As a bonus, if you don't put a type restriction in an argument you can a compile error.

**Comment by asterite** [comment]
The code is kind of hard to read because that macro is inside another macro... the `\{%` things basically say "don't execute this now, instead generate this", so later when the `method_added` macro is added to the final class it can be executed well.

**Comment by asterite** [comment]
One last thing: the name comparison should probably be `if a_def.name == "perform"`, but right now that doesn't work, I need to define comparison between string literals and macro ids.

**Comment by mperham** [comment]
Whoa, that's some metametaprogramming BUT it solves a major API compatibility issue with Sidekiq.rb: having to define arg types separately from `perform`.  THANK YOU!
