### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by Gargron** [mperham/sidekiq.cr#67]
Sidekiq in Ruby supports passing a namespace key to the redis configuration. It would be great if the same was possible in this version of Sidekiq. I've read [your blog post](http://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/) about your preference for redis DBs instead of namespaces, but I think redis DBs are very unreadable and it's easy to make a costly mistake.

**Comment by eef** [comment]
Did anything come of this or did you get it working?  I am looking to use a namespace

**Comment by mperham** [comment]
I’m not interested in supporting namespaces.
