### ISSUE TITLE
Periodic jobs

### ISSUE THREAD

**Issue by wontruefree** [mperham/sidekiq.cr#74]
Is there any way to have periodic jobs?

**Comment by wontruefree** [comment]
It looks like it is for enterprise only accounts.  Does that exist for Sidekiq.cr?

**Comment by mperham** [comment]
Oh sorry I didn’t notice this was for crystal. There is no cron functionality that I’m aware of.

**Comment by wontruefree** [comment]
Thanks I have some backup plans.  Do you have any plans or need help with a feature like this?

**Comment by mperham** [comment]
I have no plans to work on Sidekiq.cr in the future. I’m dedicated to Faktory and Faktory Pro which will have cron job support and could support Crystal if someone wants to work on a Faktory worker library in Crystal.

**Comment by wontruefree** [comment]
Thanks for the followup.
I didnt know Faktory was in active development.  I will take a look at that.
