### ISSUE TITLE
Can't run example in manjaro linux

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [mperham/sidekiq.cr#77]
Unhandled exception: Missing ENV key: "" (KeyError)
  from /usr/lib/crystal/env.cr:53:7 in 'fetch'
  from /usr/lib/crystal/env.cr:22:5 in '[]'
  from lib/sidekiq/src/sidekiq/pool.cr:27:9 in 'initialize'
  from lib/sidekiq/src/sidekiq/pool.cr:25:5 in 'initialize:pool_size'
  from lib/sidekiq/src/sidekiq/pool.cr:25:5 in 'new:pool_size'
  from lib/sidekiq/src/sidekiq/pool.cr:61:7 in 'initialize'
  from lib/sidekiq/src/sidekiq/pool.cr:60:5 in 'new'
  from lib/sidekiq/src/sidekiq/server/server.cr:40:15 in 'initialize'
  from lib/sidekiq/src/sidekiq/server/server.cr:24:5 in 'initialize:concurrency:queues:environment:logger'
  from lib/sidekiq/src/sidekiq/server/server.cr:24:5 in 'new:concurrency:queues:environment:logger'
  from lib/sidekiq/src/sidekiq/server/cli.cr:45:7 in 'create'
  from lib/sidekiq/src/sidekiq/server/cli.cr:52:7 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:86:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???

require only works with -> require "../src/sample/workers.cr"

**Comment by hugopl** [comment]
fixed by `2e38d0cf2f7d7dc5995305df612b63d112a1f1df`.
