### ISSUE TITLE
Sidekiq breaks with kemal-session shard.

### ISSUE THREAD

**Issue by franciscoGPS** [mperham/sidekiq.cr#88]
shards update throws the following error. 
I might lack sidekiq version on shard. Only branch provided.

![image](https://user-images.githubusercontent.com/6760672/84786946-01a7c380-afb3-11ea-8886-8764d506a543.png

**Comment by hugopl** [comment]
This was fixed by 2e38d0cf2f7d7dc5995305df612b63d112a1f1df.
