### ISSUE TITLE
Sidekiq web example is not compiling

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [mperham/sidekiq.cr#90]
![image](https://user-images.githubusercontent.com/12284806/97812256-e934fe80-1c5e-11eb-8678-8b21d44cb3a1.png)
![image](https://user-images.githubusercontent.com/12284806/97812268-010c8280-1c5f-11eb-9028-b366cf2942bd.png)

**Comment by omerxx** [comment]
@LeandroRezendeCoutinho Did you end up solving this?

**Comment by hugopl** [comment]
This was fixed by 3bacfcea0f0a46f40cf7ef95ed36e011954e0f57.
